name: Build & Deploy Preview

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.8'


      - name: Install dependencies
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Deploy to gh-pages-dev
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-dev
          publish_dir: _site
